### ISSUE TITLE
Support RF64 files

### ISSUE THREAD

**Issue by iluvcapra** [iluvcapra/wavinfo#3]
See #2

**Comment by emc2hahn** [comment]
Well, small files is a problem here:
The RF64 file I tested previously was from Sequoia and I just figured out that Sequoia only writes the RF64 header in files that exceed the 2GB RIFF limit. Even for short multichannel files they stick with RIFF, what surprises me.

I just created an all empty large wav that compresses down to a few MB, but be aware that it expands to over 2GB!
[Testfile_SEQ_RF64 Big.zip](https://github.com/iluvcapra/wavinfo/files/3322114/Testfile_SEQ_RF64.Big.zip)

**Comment by iluvcapra** [comment]
This is main reason I was stalling on this, the coding is one thing but setting up the test cases in a way that doesn't eat gigs of storage is a pain. WAV-RF64 promotion is part of the standard, an RF64 under 2 gigs is technically not a WAV file.

**Comment by iluvcapra** [comment]
@emc2hahn try the commit 242fa51b32b9c9de76656f5b9240b0304a8d8dd3, this appears to work.

**Comment by emc2hahn** [comment]
That is amazing, it works! I appreciate your effort a lot!
Now things are set for me to complete my metadata and file organization script.

In the long run it would be amazing if there would be also a module that allows to write the values provided by your class back into wav files but I know this will be a whole new project. I hope to find time one day to dive that deep into your code.

**Comment by iluvcapra** [comment]
I'd also like this feature and definitely is something I'd like to implement someday. For now if I need to write something back I usually use ffmpeg, which _usually_ does the right thing for my effects library management, though a lot of client apps tend to ignore this metadata or read it in a peculiar way.

Def reach out if you find anything else you'd like implemented!

**Comment by emc2hahn** [comment]
great, i'll get back in touch!

All the best so far!
