### ISSUE TITLE
Memory leak/endless loop

### ISSUE THREAD

**Issue by maxlund** [iluvcapra/wavinfo#32]
Hi,

I found a way to trigger a memory leak using `WavInfoReader("path/to/some/file.wav")` and an audio file that is corrupt, see MediaInfo output below:
```
General
Complete name                            : path/to/some/file.wav
Format                                   : Wave
Format settings                          : WaveFormatEx
File size                                : 1.20 GiB
Duration                                 : 1 h 14 min
Overall bit rate mode                    : Constant
Overall bit rate                         : 2 304 kb/s
Producer                                 : TASCAM HD-P2
Description                              : tTAPE=170406
Encoded date                             : 2017-04-06 10:25:42
Conformance errors                       : 2
 RIFF                                    : Yes
  General compliance                     : File size 1292047360 is less than expected size 1294738440 (offset 0x8)
 WAVE                                    : Yes
  General compliance                     : Element size 1294738428 is more than maximal permitted size 1292047348 (offset 0xC)

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 1 h 14 min
Bit rate mode                            : Constant
Bit rate                                 : 2 304 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Bit depth                                : 24 bits
Stream size                              : 1.20 GiB (100%)
```

Will be stuck here until we eat up all of our RAM:
```
[2024-10-25 20:25:04] Top 10 memory allocations:
Traceback (most recent call last):
wavinfo\riff_parser.py", line 33    children.append(parse_chunk(stream)) Size: 497.21 MB
```
Guessing we endlessly recurse in `parse_chunk` because the header says we have a different size than what we actually do.
Can't supply a test file unfortunately as the audio is confidential.

Just a heads up. I'm going to drop the dependency and use our ffprobe fallback for now. 
Thanks for all your work!

**Comment by maxlund** [comment]
Seeing now that we peg this to version 1.0.0 for some reason, so this may be a known issue and fixed already. Please close this and ignore if so!

**Comment by iluvcapra** [comment]
Yeah, some of these location recorders write marker/metadata segments that have invalid length.

> Seeing now that we peg this to version 1.0.0 for some reason, so this may be a known issue and fixed already. Please close this and ignore if so!

Can you tell me what version was giving you the error?

**Comment by maxlund** [comment]
1.0.0, I had my requirements.txt pegged to that and I can't find anything in the git history reminding me exactly _why_ we're using an outdated version of the lib 🙃 

I just upgraded to the latest and it runs fine. Or well, I fail to parse the timecode of the file but that is beside the point for the issue here. Feel free to close if you want!

**Comment by iluvcapra** [comment]
Okie dokie, thanks for submitting anyways it will help others.
