### ISSUE TITLE
[METADATA] Loops

### ISSUE THREAD

**Issue by wrefgtzweve** [iluvcapra/wavinfo#34]
**Describe the type of metadata you want to read:**
A loop allows you to loop parts of the sound after it has played, used often in games together with cues.

**List some applications that read and write this metadata:**
https://loopauditioneer.sourceforge.io/
A bigger list can be found here https://developer.valvesoftware.com/wiki/Looping_a_sound

**List the authorities or organizations that use and standardize this metadata:**
https://developer.valvesoftware.com/wiki/Looping_a_sound

**URL for example WAVE file with this metadata:**
https://archive.org/download/63468678/alarm_citizen_loop1.wav

**Comment by iluvcapra** [comment]
Hey thanks for submitting this! I might be wrong but isn't this just `cue` metadata? That's what the valve documentation seems to be describing. The example file doesn't have loops in the way the valve docs are describing, it seems to have a sampler `smpl` description chunk.

Cue metadata (including timed ranges) is already provided in the module; I could look into figuring out `smpl` but I'm not sure that'd help you out.

**Comment by wrefgtzweve** [comment]
At first i thought it only used cues but then noticed it wasn't picking up all the files, then i found out loops were apparently a thing.

**Comment by iluvcapra** [comment]
I think ChatGPT is just reading the articles you've already seen though. Can you send me a WAV file that has a loop in the form you're expecting?

**Comment by wrefgtzweve** [comment]
The attached file should have the loop https://archive.org/download/63468678/alarm_citizen_loop1.wav
![image](https://github.com/user-attachments/assets/2452ca89-e5aa-4064-b54b-d28325636e8c)

LoopAuditioneer:
![image](https://github.com/user-attachments/assets/43bed2a2-fdd7-499e-9271-e78fd972eaf3)

**Comment by iluvcapra** [comment]
Also... 
https://www.recordingblogs.com/wiki/sample-chunk-of-a-wave-file

**Comment by iluvcapra** [comment]
@wrefgtzweve This needs some tests written but if you want to give this reader a try it should work with what you have, or at least be a start.

**Comment by iluvcapra** [comment]
@wrefgtzweve It needs some tests written but a sampler loop reader has been implemented in PR #36 if you want to give this reader a try. It should work with what you have, or at least be a start.

**Comment by wrefgtzweve** [comment]
Tested it, seems to work for all files i tried it on 👍

**Comment by iluvcapra** [comment]
Great it's in master, I'll push a release today probably.
