### ISSUE TITLE
Add str methods to Classes

### ISSUE THREAD

**Issue by elibroftw** [iluvcapra/wavinfo#6]
When I do `print(object)` where `object` is a `WavInfoChunkReader` or `WavInfoReader`, the output should be more informative. I was thinking you should print a dictionary of their attributes.

**Comment by elibroftw** [comment]
Also, you should add a .length attribute to data

**Comment by iluvcapra** [comment]
I wouldn't want to just dump attributes there, I'd rather people do that through `walk`. Is there something specific you wanna get out of the debug? I think the `__repr__` output now isn't great I agree.

**Comment by elibroftw** [comment]
Why not? It would increase productivity and be more informative. At least some metadata?

**Comment by iluvcapra** [comment]
This is resolved in PR#8 1a3417d3e5500acfbff50894481946435f892b9e
