### ISSUE TITLE
AttributeError: 'WavBextReader' object has no attribute 'originator_date'

### ISSUE THREAD

**Issue by shrutikshirsagar** [iluvcapra/wavinfo#7]
Hi, I am trying to get the recorded date and time of my audio file (original date and time). I have installed the pip install wavinfo==1.0 on the condo virtual environment.  I am trying the following code:

print(info.bext.description)
print("----------")
print("Originator:", info.bext.originator)
print("Originator Ref:", info.bext.originator_ref)
print("Originator Date:", info.bext.originator_date)
print("Originator Time:", info.bext.originator_time)
print("Time Reference:", info.bext.time_reference)
print(info.bext.coding_history)

my error is as follows:
AttributeError                            Traceback (most recent call last)
<ipython-input-57-511caf7d9b1c> in <module>
----> 1 print(info.bext.description)
      2 print("----------")
      3 print("Originator:", info.bext.originator)
      4 print("Originator Ref:", info.bext.originator_ref)
      5 print("Originator Date:", info.bext.originator_date)

AttributeError: 'WavBextReader' object has no attribute 'description'

Please let me know if I am missing something or else, how to fix this attribute error.

Thanks a lot!

**Comment by iluvcapra** [comment]
Would you be able to post the file you're trying to read?

**Comment by iluvcapra** [comment]
Also you shouldn't be pinning the 1.0 release, I'd just install the latest.

**Comment by shrutikshirsagar** [comment]
> Would you be able to post the file you're trying to read?
Hi, thanks for your quick reply! I am not able to post my audio file here as this do not support .wav type file. I can share it on gmail.

**Comment by shrutikshirsagar** [comment]
> Also you shouldn't be pinning the 1.0 release, I'd just install the latest.

Hey, I am trying to get the original date and time of audio file. In latest version, I did not see any option for that. Please let me know if I am missing something. Thanks!

**Comment by iluvcapra** [comment]
The code you posted before should work in the latest version, none of the interface from 1.0 has changed.
